apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dell-r730-069

generatorOptions:
  disableNameSuffixHash: true

# reference: https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/#create-the-kustomization-file
secretGenerator:
- name: pullsecret-dell-r730-069
  envs:
    - .env.secret
  type: kubernetes.io/dockerconfigjson
- name: pullsecret-cluster-dell-r730-069
  envs:
    - .env.secret
  type: kubernetes.io/dockerconfigjson

resources:
- dell-r730-069.ns.yaml
- dell-r730-069.clusterdeployment.yaml
- dell-r730-069.agentclusterinstall.yaml
- dell-r730-069.infraenv.yaml
- dell-r730-069.klusterletaddonconfig.yaml
- dell-r730-069.managedcluster.yaml
