apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: mce-rolling-update
  namespace: open-cluster-management-pipelines-mce
  labels:
    app.kubernetes.io/instance: sre-pipelines
    tekton.dev/pipeline: mce-rolling-update
spec:
  params:
    - name: kubeconfig
      value: ''
    - name: start-snapshot
      value: ''
    - name: upgrade-snapshot
      value: ''
  pipelineRef:
    name: mce-rolling-update
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-storage-pvc
