apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app.kubernetes.io/instance: sre-pipelines
    tekton.dev/pipeline: mce-hypershift
  name: mce-hypershift-uninstall
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    value: ""
  - name: hostedcluster-name
    value: ""
  - name: release-image
    value: ""
  pipelineRef:
    name: mce-hypershift-uninstall
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: shared-storage-pvc
