apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app.kubernetes.io/instance: sre-pipelines
    tekton.dev/pipeline: mce-hypershift-e2e
  name: mce-hypershift-e2e
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    value: ""
  - name: hostedcluster-name
    value: ""
  - name: release-image
    value: ""
  - name: start-snapshot
    value: 2.7.0-DOWNSTREAM-2022-10-07-00-46-31
  - name: upgrade-snapshot
    value: 2.7.0-DOWNSTREAM-2022-10-28-18-36-56
    # value: 2.7.0-DOWNSTREAM-2022-10-07-00-46-31
    # value: 2.7.0-DOWNSTREAM-2022-10-24-01-24-39
    # value: 2.7.0-DOWNSTREAM-2022-10-28-18-36-56 - successful
    # value: 2.7.0-DOWNSTREAM-2022-10-20-05-23-04 - successful
  pipelineRef:
    name: mce-hypershift-e2e
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: shared-storage-pvc
