---

- name: "Getting namespaces"
  kubernetes.core.k8s_info:
    kind: Namespace
    host: "{{ cluster_proxy.cluster_url }}"
    validate_certs: false
    api_key: "{{ managed_serviceaccount.token }}"
  register: ns_list

- name: Print namespaces
  ansible.builtin.debug:
    msg: "{{ item.metadata.name }}"
  loop: "{{ ns_list.resources }}"

- name: Get a list of all pods in namespace open-cluster-management-agent-addon
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: open-cluster-management-agent-addon
    host: "{{ cluster_proxy.cluster_url }}"
    validate_certs: false
    api_key: "{{ managed_serviceaccount.token }}"
  register: pod_list

- name: Print pod list for namespace open-cluster-management-agent-addon
  ansible.builtin.debug:
    msg: "{{ pod_list }}"
