---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-cert-manager-catalog
  namespace: redhat-cert-manager-operator
spec:
  displayName: cdoan Cert Manager
  image: quay.io/osd-addons/cert-manager-operator-index@sha256:5948dff38e069289b710f5a1d8de7e5b6d2bae36bdb33d13e4a4d7a282ce89d9
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
