apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mce-automation-pipelines
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/openshift-pipelines/lab-mce
    repoURL: https://github.com/cdoan1/examples.acm.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
