---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eso
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: "null"
        url: "null"
  template:
    metadata:
      name: '{{cluster}}-eso'
    spec:
      destination:
        namespace: openshift-gitops
        server: '{{url}}'
      project: default
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.5.9
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
