---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    installer.name: multiclusterhub
    installer.namespace: redhat-open-cluster-management
    multiclusterhubs.operator.open-cluster-management.io/managed-by: "true"
    operators.coreos.com/multicluster-engine.multicluster-engine: ""
  name: multicluster-engine
  namespace: multicluster-engine
spec:
  channel: beta
  installPlanApproval: Automatic
  name: multicluster-engine
  source: addon-advanced-cluster-management-catalog
  sourceNamespace: openshift-marketplace