---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-advanced-cluster-management-catalog
  namespace: redhat-open-cluster-management
spec:
  displayName: Advanced Cluster Management
  # 2.7.1-1
  # efeff87
  image: quay.io/osd-addons/advanced-cluster-management-index:efeff87
  # image: quay.io/osd-addons/advanced-cluster-management-index:b2bc431
  # image: quay.io/osd-addons/advanced-cluster-management-index:b1a9818
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-advanced-cluster-management-catalog
  namespace: openshift-marketplace
spec:
  displayName: MultiCluster Engine
  image: quay.io/osd-addons/advanced-cluster-management-index:b1a9818
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
