apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
spec:
  channel: release-2.5
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: acm-custom-registry
  sourceNamespace: open-cluster-management
  startingCSV: advanced-cluster-management.v2.5.0
