apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: acm-custom-registry
    newName: quay.io:443/acm-d/acm-custom-registry
    newTag: 2.4.0-DOWNSTREAM-2021-10-25-23-58-51
    # newTag: 2.4.0-DOWNSTREAM-2021-10-20-16-17-48
    # newTag: 2.4.0-DOWNSTREAM-2021-10-06-20-31-30
    # newTag: 2.4.0-DOWNSTREAM-2021-09-23-08-29-45

resources:
  - open-cluster-management-ns.yaml
  - open-cluster-management-operatorgroup.yaml
  - custom-registry-deployment.yaml
  - custom-registry-service.yaml
  - catalog-source.yaml
  - advanced-cluster-management-sub.yaml
