apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-cert-manager
  namespace: redhat-cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: beta
  installPlanApproval: Automatic
  name: cert-manager-operator
  source: addon-cert-manager-catalog
  sourceNamespace: redhat-cert-manager
