apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-pipelines-vault

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- vault_e2e.yaml
- task_vault_setup.yaml
- task_argocd_import.yaml
- task_deploy_cert_manager.yaml
- shared-workspace-pvc.yaml
