---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-cert-manager
spec:
  params:
  - name: cluster-name
    default: ""
    description: "OPTIONAL - name of managed cluster to install vault, by default, we'll create a clusterclaim"
    type: string
  - name: clusterClaimName
    default: ""
    type: string
  steps:
  - args:
    - |-
      set -e
      set -x

      oc get secret cert-manager-dns-credentials -oyaml > cert-manager-dns-credentials.yaml

      TOP=$(pwd)
      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/patch-operator/overlay/dev

      # hack
      oc --kubeconfig=$TOP/remote.kubeconfig adm policy add-cluster-role-to-user cluster-admin \
        system:serviceaccount:patch-operator:mutatingwebhook-patcher

      sleep 60
      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/cert-manager/overlay/dev

      sleep 60
      oc --kubeconfig=$TOP/remote.kubeconfig adm oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:cert-manager:cert-manager
      
      oc --kubeconfig=$TOP/remote.kubeconfig apply -f cert-manager-dns-credentials.yaml -n cert-manager

      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/patch-operator-config/base

      sleep 60
      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/cert-manager-config/overlay/dev

      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/cdoan_rh22/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
