---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-cert-manager
spec:
  params:
  - name: cluster-name
    default: ""
    description: "OPTIONAL - name of managed cluster to install vault, by default, we'll create a clusterclaim"
    type: string
  - name: clusterClaimName
    default: ""
    type: string
  steps:
  - args:
    - |-
      set -e

      TOP=$(pwd)

      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/patch-operator/overlay/dev
      oc --kubeconfig=$TOP/remote.kubeconfig apply -k gitops/argocd/cert-manager/overlay/dev

      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/cdoan_rh22/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
