---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: patch-operator-inject
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: patch-operator-controller-manager-service
      namespace: patch-operator
      path: /inject
    caBundle: Cg==
  failurePolicy: Fail
  name: patch-operator-inject.redhatcop.redhat.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - configmaps
  - apiGroups:
    - "cert-manager.io"
    - "acme.cert-manager.io"
    apiVersions:
    - "v1"
    operations:
    - CREATE
    - UPDATE
    resources:
    - "*/*"
  - apiGroups:
    - "config.openshift.io"
    apiVersions:
    - "v1"
    operations:
    - CREATE
    - UPDATE
    - CONNECT
    resources:
    - "*/*"
  sideEffects: None
