---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acm-rolling-upgrade-27
  namespace: open-cluster-management-pipelines-upgrade
spec:
  params:
  - name: namespace
    type: string
    description: The namespace to deploy ACM onto the target cluster
    default: "open-cluster-management"
  - name: upgrade-snapshot
    type: string
    description: The downstream snapshot to used to deploy ACM
    default: "2.7.0-DOWNSTREAM-2022-11-17-03-53-08"
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/stolostron/deploy.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace

  - name: delete-mco
    runAfter:
    - fetch-repo
    taskRef:
      name: delete-mco
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: upgrade-27
    runAfter:
    - delete-mco
    params:
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: upgrade-27
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: create-mco
    runAfter:
    - upgrade-27
    taskRef:
      name: create-mco
    workspaces:
    - name: source
      workspace: shared-workspace

  workspaces:
  - name: shared-workspace

