apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-custom-registry
  namespace: open-cluster-management
  labels:
    app: acm-custom-registry
spec:
  selector:
    matchLabels:
      app: acm-custom-registry
  template:
    metadata:
      labels:
        app: acm-custom-registry
    spec:
      containers:
      - name: acm-custom-registry
        image: acm-custom-registry:1.0.0
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mce-custom-registry
  namespace: multicluster-engine
  labels:
    app: mce-custom-registry
spec:
  selector:
    matchLabels:
      app: mce-custom-registry
  template:
    metadata:
      labels:
        app: mce-custom-registry
    spec:
      containers:
      - name: mce-custom-registry
        image: mce-custom-registry:1.0.0
        ports:
        - containerPort: 50051
