apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
  namespace: redhat-open-cluster-management
spec:
  targetNamespaces:
    - redhat-open-cluster-management

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
  namespace: multicluster-engine
spec:
  targetNamespaces:
    - multicluster-engine
