apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-pipelines-mce

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- shared-workspace-pvc.yaml
- mce-hypershift.yaml
- mce-hypershift-uninstall.yaml
- mce_hypershift_e2e.yaml
- mce_hypershift_27_27_e2e.yaml
- mce_hypershift_ocm_addon.yaml
- task_mce_enable_kubeconfig.yaml
- task_mce_install_acm.yaml
- task_mce_install_acm_26.yaml
- task_mce_wait_ready.yaml
- task_mce_check_status.yaml
- task_mce_rolling_upgrade_acm.yaml
- task_mce_rolling_upgrade_acm_26.yaml
- task_mce_hypershift_build_hypershift_cli.yaml
- task_mce_hypershift_enable_hypershift.yaml
- task_mce_hypershift_create_hostedcluster.yaml
- task_mce_hypershift_delete_hostedcluster.yaml
- task_mce_hypershift_create_hostedcluster_external_dns.yaml
- task_mce_uninstall_acm.yaml
- task_mce_uninstall_acm_post_cleanup.yaml
- mce_hypershift_clusterpool_flow.yaml
- task_checkoutCluster.yaml
- task_loginToCluster.yaml
- task_notifyStatus.yaml
- task_applyPrereqsDownstream.yaml
- task_mce_hypershift_create_ocm_cluster.yaml
- task_mce_hypershift_create_ocm_cluster_wait_for_ocm.yaml
- task_mce_hypershift_create_ocm_cluster_ensure_acm_ocm_addon.yaml
