apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-pipelines-mce

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- shared-workspace-pvc.yaml
- mce-hypershift.yaml
- mce-hypershift-uninstall.yaml
- mce_hypershift_e2e.yaml
- task_mce_enable_kubeconfig.yaml
- task_mce_install_acm.yaml
- task_mce_wait_ready.yaml
- task_mce_check_status.yaml
- task_mce_rolling_upgrade_acm.yaml
- task_mce_hypershift_enable_hypershift.yaml
- task_mce_hypershift_create_hostedcluster.yaml
- task_mce_uninstall_acm.yaml
- task_mce_uninstall_acm_post_cleanup.yaml
