apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-pipelines-mce

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- mce-hypershift.yaml
- shared-workspace-pvc.yaml
