apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-pipelines-mce

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- mce-hypershift.yaml
- task_mce_enable_kubeconfig.yaml
- task_mce_install_acm.yaml
- task_mce_check_status.yaml
- task_mce_hypershift_create_hostedcluster.yaml
- shared-workspace-pvc.yaml
