---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mce-hypershift
  namespace: open-cluster-management-pipelines-mce
  description: "1. Enable hypershoft 2. Create a hostedcluster."
spec:
  params:
  - name: kubeconfig
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    default: ""
    type: string
  - name: hostedcluster-name
    type: string
    description: "hostedcluster name to create."
    default: ""
  - name: release-image
    type: string
    description: "ocp release image version to install the hostedcluster."
    default: ""
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/cdoan1/examples.acm.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: enable-hypershift
    runAfter:
    - fetch-repo
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-hypershift-enable-hypershift
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: create-hostedcluster
    runAfter:
    - enable-hypershift
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-hypershift-create-hostedcluster
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-hypershift-enable-hypershift
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  steps:
  - args:
    - |-
      set -e

      export K=$(params.kubeconfig)
      ./hack/mce-sanity-check.sh

      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-hypershift-create-hostedcluster
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  steps:
  - args:
    - |-
      set -e

      export K=$(params.kubeconfig)
      ./hack/mce-sanity-check.sh

      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
