---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mce-rolling-update
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    type: string
    description: "base64 encoded kubeconfig."
    default: ""
  - name: start-snapshot
    type: string
    description: "snapshot version to initially install."
    default: ""
  - name: upgrade-snapshot
    type: string
    description: "snapshot version to upgrade too. example: 2.7.0-DOWNSTREAM-2022-11-03-10-46-20"
    default: ""

  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/cdoan1/examples.acm.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace

  # in case we want to test on a managed cluster
  - name: enable-kubeconfig
    runAfter:
    - fetch-repo
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-enable-kubeconfig
    workspaces:
    - name: source
      workspace: shared-workspace
    
  - name: wait-ready
    runAfter:
    - enable-kubeconfig
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-wait-ready
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: check-status
    runAfter:
    - wait-ready
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-check-status
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: rolling-upgrade
    runAfter:
    - check-status
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: mce-rolling-upgrade-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: rolling-upgrade-wait-ready
    runAfter:
    - rolling-upgrade
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-wait-ready
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: rolling-upgrade-check-status
    runAfter:
    - rolling-upgrade-wait-ready
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-check-status
    workspaces:
    - name: source
      workspace: shared-workspace
    
  workspaces:
  - name: shared-workspace
