---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mce-hypershift-e2e
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    default: ""
    type: string
  - name: hostedcluster-name
    type: string
    description: "hostedcluster name to create."
    default: ""
  - name: release-image
    type: string
    description: "ocp release image version to install the hostedcluster."
    default: ""
  - name: start-snapshot
    type: string
    description: "snapshot version to initially install."
    default: "2.7.0-DOWNSTREAM-2022-10-07-00-46-31"
  - name: upgrade-snapshot
    type: string
    description: "snapshot version to upgrade too."
    default: "2.7.0-DOWNSTREAM-2022-10-20-05-23-04"

  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/cdoan1/examples.acm.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: enable-kubeconfig
    runAfter:
    - fetch-repo
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-enable-kubeconfig
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: uninstall-acm
    runAfter:
    - enable-kubeconfig
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    - name: start-snapshot
      value: $(params.start-snapshot)
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: mce-uninstall-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: post-cleanup
    runAfter:
    - uninstall-acm
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    - name: start-snapshot
      value: $(params.start-snapshot)
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: mce-uninstall-acm-post-cleanup
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: deploy-acm
    runAfter:
    - post-cleanup
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    - name: start-snapshot
      value: $(params.start-snapshot)
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: mce-install-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: wait-ready
    runAfter:
    - deploy-acm
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-wait-ready
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: check-status
    runAfter:
    - wait-ready
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-check-status
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: rolling-upgrade
    runAfter:
    - check-status
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    - name: upgrade-snapshot
      value: $(params.upgrade-snapshot)
    taskRef:
      name: mce-rolling-upgrade-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: rolling-upgrade-wait-ready
    runAfter:
    - rolling-upgrade
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-wait-ready
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: rolling-upgrade-check-status
    runAfter:
    - rolling-upgrade-wait-ready
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-check-status
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: enable-hypershift
    runAfter:
    - rolling-upgrade-check-status
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-hypershift-enable-hypershift
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: create-hostedcluster
    runAfter:
    - enable-hypershift
    params:
    - name: kubeconfig
      value: $(params.kubeconfig)
    taskRef:
      name: mce-hypershift-create-hostedcluster
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
