---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mce-hypershift-clusterpool-flow
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: clusterPoolName
    type: string
    description: The name of the clusterpool to use
    default: "hypershift-cluster-pool"
  - name: clusterClaimName
    type: string
    description: The name of the clusterclaim to claim
    default: "hs-ci-ds-cluster-playback"
  - name: clusterClaimLifetime
    type: string
    description: The length of the lifetime of the clusterclaim. Default 8h
    default: "8h"
  - name: namespace
    type: string
    description: The namespace to deploy ACM onto the target cluster
    default: "open-cluster-management"
  - name: snapshot
    type: string
    description: The downstream SNAPSHOT to used to deploy ACM
    default: "2.0-latest"
  - name: sendNotification
    type: string
    description: Sends notification to slack if value is true
    default: "false"
  - name: start-snapshot
    type: string
    description: "snapshot version to initially install."
    default: "2.7.0-DOWNSTREAM-2022-10-07-00-46-31"
  - name: upgrade-snapshot
    type: string
    description: "snapshot version to upgrade too."
    default: "2.7.0-DOWNSTREAM-2022-10-20-05-23-04"

  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/cdoan1/examples.acm.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: checkout-hub-cluster
    runAfter:
    - fetch-repo
    params:
    - name: clusterClaimName
      value: $(params.clusterClaimName)
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    taskRef:
      name: deploy-acm-hyper-checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace


  workspaces:
  - name: shared-workspace

