apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-e2e
  namespace: open-cluster-management-pipelines-mce
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
