---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-uninstall-acm-post-cleanup
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "cdoan-hosting-cluster"
    description: "name of the managed cluster to run tasks on."
    type: string
  - name: start-snapshot
    default: "2.7.0-DOWNSTREAM-2022-10-07-00-46-31"
    description: "sprint 18"
    type: string
  - name: upgrade-snapshot
    default: "2.7.0-DOWNSTREAM-2022-10-20-05-23-04"
    description: "sprint 19"
    type: string
  steps:
  - args:
    - |-
      set -e

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      else
        echo "remote kubeconfig not found"
        exit 1
      fi
      
      oc cluster-info

      # hack to set/update the snapshot version
      KUSTOM=./gitops/kustomization/rhacm-operator/base-downstream-release-2.7-acm-d/kustomization.yaml
      S=$(params.start-snapshot)
      echo "Updating start-snapshot: $S"
      cat $KUSTOM | sed -r "s/    newTag: 2.7.0-DOWNSTREAM-2022-10-25-02-23-54/    newTag: $S/g" > temp.yaml
      mv temp.yaml $KUSTOM

      NS=open-cluster-management

      set -x
      if [[ $(oc get pods -n $NS -o name | wc -l) -gt 0 ]]; then
        oc get deployment -n $NS -o name | xargs -I % oc delete % -n $NS
      fi
      oc get catalogsource -n $NS -o name | xargs -I % oc delete % -n $NS
      set +x
      
      echo "wait 60s"
      sleep 60
      
      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
