---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-install-acm
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  steps:
  - args:
    - |-
      set -e

      export K=$(params.kubeconfig)
      if [ -z $K ]; then
        echo "kubeconfig is empty, check if this is a managed cluster, and we have the kubeconfig."
        if [ "$(params.managed-cluster)" != "" ]]; then
          echo "found managed cluster $(params.managed-cluster)"
          if oc get secret -n cdoan-hosting-cluster -l hive.openshift.io/secret-type=kubeconfig -o name; then
            _SECRET=$(oc get secret -n cdoan-hosting-cluster -l hive.openshift.io/secret-type=kubeconfig -o name)
            oc extract $_SECRET -n $_MANAGED_CLUSTER --confirm
          fi
        else
          exit 1
        fi
      fi

      ./hack/mce-sanity-check.sh

      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
