---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-hypershift-enable-hypershift
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "osdprestaging"
    description: "name of this managed cluster, will use this value to construct the hostedcluster name."
    type: string
  steps:
  - args:
    - |-
      set -e

      # oc extract secret/aws-credentials --confirm
      mkdir ~/.aws
      cp credentials ~/.aws

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      else
        echo "Expected to find remote.kubeconfig. Existing."
        exit 1
      fi
      
      oc cluster-info

      oc patch mce multiclusterengine --type=merge \
        -p '{"spec":{"overrides":{"components":[{"name":"hypershift-preview","enabled": true}]}}}'

      OIDC_BUCKET_NAME=playbacknext-hypershift
      OIDC_BUCKET_REGION=us-west-1
      BASE_DOMAIN=demo.red-chesterfield.com

      # CLUSTER_NAME=$(params.managed-cluster)-hostedcluster
      REGION=us-west-1

      aws s3api create-bucket --acl public-read --bucket $OIDC_BUCKET_NAME \
        --create-bucket-configuration LocationConstraint=$OIDC_BUCKET_REGION \
        --region $OIDC_BUCKET_REGION || true

      aws s3 ls | grep $OIDC_BUCKET_NAME
      
      oc create secret generic hypershift-operator-oidc-provider-s3-credentials \
        --from-file=credentials=credentials \
        --from-literal=bucket=$OIDC_BUCKET_NAME \
        --from-literal=region=$OIDC_BUCKET_REGION \
        -n local-cluster || true

      _aws_access_key_id=$(cat credentials | grep aws_access_key_id | cut -d'=' -f2 | tr -d " ")
      _aws_secret_access_key=$(cat credentials | grep aws_secret_access_key | cut -d'=' -f2 | tr -d " ")

      # TODO(cdoan): Add a check for 2.7.0 only, 2.6.2 does not have this support?
      oc create secret generic hypershift-operator-external-dns-credentials \
        --from-literal=aws-access-key-id=$_aws_access_key_id \
        --from-literal=aws-secret-access-key=$_aws_secret_access_key \
        --from-literal=provider=aws \
        --from-literal=domain-filter=stolostron.io \
        --from-literal=txt-owner-id=cdoan \
        -n local-cluster || true

      oc apply -f - <<EOF
      apiVersion: addon.open-cluster-management.io/v1alpha1
      kind: ManagedClusterAddOn
      metadata:
        name: hypershift-addon
        namespace: local-cluster
      spec:
        installNamespace: open-cluster-management-agent-addon
      EOF
      
      oc get managedclusteraddons -n local-cluster hypershift-addon

      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
