---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-wait-ready
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "osdprestaging"
    description: "name of the managed cluster to run tasks on."
    type: string
  steps:
  - args:
    - |-
      set -x

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      else
        exit 1
      fi
      
      oc cluster-info

      NS=open-cluster-management
      NS2=multicluster-engine

      date -u
      oc wait --for="condition=Complete" mch multiclusterhub -n open-cluster-management --timeout=600s
      oc wait --for="condition=Available" mce multiclusterengine -n multicluster-engine --timeout=900s
      date -u
      
      mce_current_csv=$(oc get sub -n multicluster-engine -ojsonpath='{.items[].status.currentCSV}')
      _mce_csv_condition=$(oc get csv -n multicluster-engine $mce_current_csv -ojsonpath='{.status.conditions[-1].phase}')

      ace_current_csv=$(oc get sub -n open-cluster-management -l operators.coreos.com/advanced-cluster-management.open-cluster-management= -ojsonpath='{.items[].status.currentCSV}')
      _acm_csv_condition=$(oc get csv -n open-cluster-management $ace_current_csv -ojsonpath='{.status.conditions[-1].phase}')

      echo " mce csv: $_mce_csv_condition"
      echo " acm csv: $_acm_csv_condition"

      if [[ $_mce_csv_condition != "Succeeded" ]] || [[ $_acm_csv_condition != "Succeeded" ]]; then
        echo "operator csv failed to complete."
        exit 1
      fi
      
      echo "done with waiting."
      set +x
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
