---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-install-acm-26
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: skip26
    default: "false"
    description: ""
    type: string
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "osdprestaging"
    description: "name of the managed cluster to run tasks on."
    type: string
  - name: start-snapshot
    default: "v2.6.2-RC2"
    description: "2.6.2"
    type: string
  - name: upgrade-snapshot
    default: ""
    description: "none"
    type: string
  steps:
  - args:
    - |-
      set -e
      set -x

      if [[ "$(params.skip26)" == "true" ]]; then
        exit 0
      fi

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      else
        exit 1
      fi
      
      oc cluster-info

      # hack to set/update the snapshot version
      KUSTOM=./gitops/kustomization/rhacm-operator/base-downstream-release-2.6-acm-d-catalogsource/kustomization.yaml
      S=$(params.start-snapshot)
      echo "Updating start-snapshot: $S"
      cat $KUSTOM | sed -r "s/    newTag: v2.6.1-RC1/    newTag: $S/g" > temp.yaml
      mv temp.yaml $KUSTOM

      SOURCE=./gitops/kustomization/rhacm-operator/base-downstream-release-2.7-acm-d-catalogsource/catalog-source.yaml
      cat $SOURCE | sed -r "s/v2.6.1-RC1/$S/g" > temp.yaml
      mv temp.yaml $SOURCE

      oc apply -k ./gitops/kustomization/rhacm-operator/base-downstream-release-2.6-acm-d-catalogsource

      sleep 60
      oc wait --for condition=Ready pods -n open-cluster-management -l name=multiclusterhub-operator --timeout=300s || true
      
      # todo(cdoan): hack create the mch pull secret
      oc get secret pull-secret -n openshift-config -o yaml \
        | sed "s/namespace: openshift-config/namespace: open-cluster-management/g" \
        | sed "s/name: pull-secret/name: multiclusterhub-operator-pull-secret/g" \
        | sed "/  resourceVersion:/d" \
        | sed "/  uid:/d" \
        | sed "/  creationTimestamp:/d" \
        | oc apply -f -
      
      oc apply -k ./gitops/kustomization/rhacm-instance/overlays/downstream-release-2.6-catalogsource
      
      set +x
      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
