apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-attach-managed-cluster
spec:
  params:
  - name: clusterClaimName
    default: demo-claim
    description: The name of the clusterclaim to use
    type: string
  results:
  - name: username
    description: Username for the claimed cluster.
  - name: password
    description: Password for the claimed cluster.  
  - name: api
    description: API URL of the claimed cluster.
  - name: imagePullSecret
    description: The imagePullSecret on the hub cluster.
  steps:
  - args:
    - |-
      set -ex


      if [ ! -f $(pwd)/remote.kubeconfig ]; then
        exit 1
      fi

      export KUBECONFIG=$(pwd)/remote.kubeconfig
      
      oc cluster-info
      
      echo "# Copyright Contributors to the Open Cluster Management project
      managedCluster:
        name: ""
        addons:
          applicationManager:
            enabled: false
          policyController:
            enabled: true
          searchCollector:
            enabled: false
          certPolicyController:
            enabled: true
          iamPolicyController:
            enabled: true
        autoImportRetry: 5" > spokevalues.yaml

      cm attach cluster --cluster $(inputs.params.clusterClaimName) --cluster-kubeconfig managedcluster.kubeconfig --values spokevalues.yaml

      oc wait --for="condition=ManagedClusterConditionAvailable" managedcluster $(inputs.params.clusterClaimName) --timeout=600s || true

      echo "Managed Cluster successfully imported"
      exit 0 
    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
