---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-hypershift-delete-hostedcluster
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "chc"
    description: "name of this managed cluster, will use this value to construct the hostedcluster name."
    type: string
  steps:
  - args:
    - |-
      set -e
      set -x

      TOP=$(pwd)
      PULL_SECRET=$TOP/pull-secret-hypershift.json
      export NS=open-cluster-management-pipelines-rhacm
      oc get secret multiclusterhub-operator-pull-secret-basic -n $NS -ojsonpath='{.data.\.dockerconfigjson}' | base64 --decode > $PULL_SECRET

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      else
        echo "Expected to find remote.kubeconfig. Existing."
        exit 1
      fi

      oc cluster-info
      
      OIDC_BUCKET_NAME=playbacknext-hypershift
      OIDC_BUCKET_REGION=us-west-1
      BASE_DOMAIN=demo.red-chesterfield.com
      # RELEASE=quay.io/openshift-release-dev/ocp-release:4.11.11-x86_64

      CLUSTER_NAME=$(params.managed-cluster)-hostedcluster
      INFRA_ID=$CLUSTER_NAME
      REGION=us-west-1

      if [ ! -f $AWS_CREDS ]; then
        echo "Requires AWS credentials file."
        exit 1
      fi

      AWS_CREDS=credentials
      OUTPUT_INFRA_FILE=$TOP/hypershift_test_infra.json
      OUTPUT_IAM_FILE=$TOP/hypershift_test_iam.json
      export HYPERSHIFT=$(pwd)/hypershift/bin/hypershift.12


      list=$(oc get hostedcluster -n local-cluster -o name)
      for i in $list
      do
        echo $i
        oc delete % -n local-cluster
      done


      echo "Done with hostedcluster task ..."

      set +x
      set +e
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
