---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mce-rolling-upgrade-acm
  namespace: open-cluster-management-pipelines-mce
spec:
  params:
  - name: skip26
    default: "false"
    description: "skip this task"
    type: string
  - name: kubeconfig
    default: ""
    description: "base64 encoded kubeconfig of the cluster we want to run this task on. Default to empty string, use the current cluster."
    type: string
  - name: managed-cluster
    default: "osdprestaging"
    description: "name of the managed cluster to run tasks on."
    type: string
  - name: start-snapshot
    default: "2.7.0-DOWNSTREAM-2022-10-07-00-46-31"
    description: "sprint 18"
    type: string
  - name: upgrade-snapshot
    default: "2.7.0-DOWNSTREAM-2022-10-20-05-23-04"
    description: "sprint 19"
    type: string
  steps:
  - args:
    - |-
      set -e
      set -x

      if [ -f $(pwd)/remote.kubeconfig ]; then
        export KUBECONFIG=$(pwd)/remote.kubeconfig
      fi
      
      oc cluster-info

      # 1. Operator
      #
      # oc apply -k ./gitops/kustomization/rhacm-operator/base-downstream-release-2.7.0-acm-ocm-addon-3.7.0-pre2
      
      oc apply -f ./gitops/kustomization/rhacm-operator/base-downstream-release-2.7.0-acm-ocm-addon-3.7.0-pre2/catalog-source.yaml


      sleep 60

      oc wait --for condition=Ready pods -n open-cluster-management -l name=multiclusterhub-operator --timeout=120s
      
      # 2. Operand
      #
      # todo(cdoan): hack create the mch pull secret
      # oc get secret pull-secret -n openshift-config -o yaml \
      #   | sed "s/namespace: openshift-config/namespace: open-cluster-management/g" \
      #   | sed "s/name: pull-secret/name: multiclusterhub-operator-pull-secret/g" \
      #   | sed "/  resourceVersion:/d" \
      #   | sed "/  uid:/d" \
      #   | sed "/  creationTimestamp:/d" \
      #   | oc apply -f -
      
      # oc apply -k ./gitops/kustomization/rhacm-instance/overlays/addon-release-2.7.0-acm-ocm-addon-3.7.0-pre2

      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
