apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - open-cluster-management-ns.yaml
  - open-cluster-management-operatorgroup.yaml
  - catalog-source.yaml
  - advanced-cluster-management-sub.yaml
  # - rhacm-repo.yaml
