apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: redhat-open-cluster-management
  annotations:
    installer.open-cluster-management.io/mce-subscription-spec: '{"channel":"stable","installPlanApproval":"Automatic","name":"multicluster-engine","source":"addon-rhacm-catalog","sourceNamespace":"openshift-marketplace"}'
spec:
  availabilityConfig: Basic
