apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: stable
  installPlanApproval: Manual
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-manager.v1.10.1
  # config:
  #   resources:
  #     requests:
  #       memory: "300Mi"
  #       cpu: "100m"
  #     limits:
  #       memory: "2Gi"
