apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  namespace: open-cluster-management
  name: multiclusterhub
spec:
  availabilityConfig: High
  imagePullSecret: multiclusterhub-operator-pull-secret
  nodeSelector:
    node-role.kubernetes.io/infra: ""