apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: alpha
  installPlanApproval: Automatic
  # name: openshift-cert-manager-operator
  # name: cert-manager-operator
  # name: cert-manager-operator-addon - if this is the folder name, is this this SKU name
  # name: cert-manager-operator
  name: openshift-cert-manager-operator
  source: addon-cert-manager-catalog
  sourceNamespace: cert-manager
  config:
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "2Gi"
