---
kind: CatalogSource
metadata:
  name: acm-custom-registry
  namespace: open-cluster-management
spec:
  displayName: Advanced Cluster Management
  image: quay.io:443/acm-d/acm-custom-registry:2.7.0-DOWNSTREAM-2022-10-25-02-23-54
  publisher: Red Hat
  secrets:
  - multiclusterhub-operator-pull-secret
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mce-custom-registry
  namespace: multicluster-engine
spec:
  displayName: MultiCluster Engine
  image: quay.io:443/acm-d/mce-custom-registry:2.7.0-DOWNSTREAM-2022-10-25-02-23-54
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
