---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-advanced-cluster-management-catalog
  namespace: redhat-open-cluster-management
spec:
  displayName: Advanced Cluster Management
  image: quay.io/osd-addons/advanced-cluster-management-index@sha256:b668ef46db8431501176aae701282bea6ab431272bd30b6ab63563823743da6b
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-advanced-cluster-management-catalog
  namespace: openshift-marketplace
spec:
  displayName: MultiCluster Engine
  image: quay.io/osd-addons/advanced-cluster-management-index@sha256:b668ef46db8431501176aae701282bea6ab431272bd30b6ab63563823743da6b
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
